name: dry run CI
on:
  push:
    branches:
      - dev
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main


env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: Dry run ${{ matrix.inputtype }}-${{ matrix.profile }} pipeline test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.1"
          - "latest"
        inputtype:
          - fasta
          - illumina
          - nanopore
        profile: ["docker", "conda"] # TODO "singularity"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: /usr/local/bin/nextflow
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-nextflow-

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1

      - name: Set up miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}

      - name: Conda clean
        if: matrix.profile == 'conda'
        run: conda clean -a

      - name: Run nf-test
        run: nf-test test --profile=${{ matrix.profile }} tests/${{ matrix.inputtype }}/*.nf.test --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap
